// #include <sys/types.h>
// #include <stdlib.h>
 #include <stddef.h>
// #include <sys/cdefs.h>
#include <stdio.h>
// #include <complex.h>
// #include <ctype.h>
// #include <err.h>
// #include <errno.h>
// #include <sys/errno.h>
// #include <fenv.h>
// #include <inttypes.h>
// #include <locale.h>
// #include <math.h>
// #include <setjmp.h>
// #include <signal.h>
// #include <stdlib.h>
// #include <string.h>
// #include <time.h>
// #include <wchar.h>
// #include <wctype.h>
// #include <aio.h>
// #include <arpa/inet.h>
// #include <cpio.h>
// #include <dirent.h>
// #include <dlfcn.h>
// #include <fcntl.h>
// #include <sys/fcntl.h>
// #include <fmtmsg.h>
// #include <fnmatch.h>
// #include <ftw.h>
// #include <glob.h>
// #include <grp.h>
// #include <iconv.h>
// #include <ifaddrs.h>
// #include <sys/ioctl.h>
// #include <langinfo.h>
// #include <libgen.h>
// #include <monetary.h>
// #include <netdb.h>
// #include <net/if.h>
// #include <netinet/in.h>
// #include <netinet/tcp.h>
// #include <nl_types.h>
// #include <poll.h>
// #include <sys/poll.h>
// #include <pthread.h>
// #include <pwd.h>
// #include <regex.h>
// #include <sched.h>
// #include <search.h>
// #include <semaphore.h>
// #include <spawn.h>
// #include <strings.h>
// #include <sys/ipc.h>
// #include <sys/mman.h>
// #include <sys/msg.h>
// #include <sys/resource.h>
// #include <sys/select.h>
// #include <sys/sem.h>
// #include <sys/shm.h>
// #include <sys/socket.h>
// #include <sys/stat.h>
// #include <sys/statvfs.h>
// #include <sys/time.h>
// #include <sys/times.h>
// #include <sys/uio.h>
// #include <sys/un.h>
// #include <sys/utsname.h>
// #include <sys/wait.h>
// #include <sys/xattr.h>
// #include <syslog.h>
// #include <sys/syslog.h>
// #include <tar.h>
// #include <termios.h>
// #include <sys/termios.h>
// #include <ulimit.h>
// #include <unistd.h>
// #include <sys/unistd.h>
// #include <utime.h>
// #include <utmpx.h>
// #include <wordexp.h>
// #include <getopt.h>
// #include <locale.h>
// #include <wctype.h>
// #include <alloca.h>
// #include <net/if.h>
// #include <pthread.h>
// #include <sys/file.h>
// #include <sys/mount.h>
// #include <sys/param.h>
// #include <sys/queue.h>
// #include <sys/quota.h>
// #include <sys/signal.h>
// #include <sys/syscall.h>
// #include <sys/sysctl.h>
// #include <sys/timeb.h>
// #include <sys/ttydefaults.h>
// #include <sys/ucontext.h>
// #include <uuid/uuid.h>
// #include <sysexits.h>
// #include <libxml2/libxml/HTMLparser.h>
// #include <libxml2/libxml/SAX.h>
// #include <libxml2/libxml/SAX2.h>
// #include <libxml2/libxml/globals.h>
// #include <libxml2/libxml/parser.h>
// #include <libxml2/libxml/threads.h>
// #include <libxml2/libxml/tree.h>
// #include <libxml2/libxml/xlink.h>
// #include <libxml2/libxml/xmlmemory.h>
// #include <libxml2/libxml/HTMLtree.h>
// #include <libxml2/libxml/c14n.h>
// #include <libxml2/libxml/catalog.h>
// #include <libxml2/libxml/chvalid.h>
// #include <libxml2/libxml/debugXML.h>
// #include <libxml2/libxml/dict.h>
// #include <libxml2/libxml/encoding.h>
// #include <libxml2/libxml/entities.h>
// #include <libxml2/libxml/hash.h>
// #include <libxml2/libxml/list.h>
// #include <libxml2/libxml/nanoftp.h>
// #include <libxml2/libxml/nanohttp.h>
// #include <libxml2/libxml/parserInternals.h>
// #include <libxml2/libxml/pattern.h>
// #include <libxml2/libxml/relaxng.h>
// #include <libxml2/libxml/schemasInternals.h>
// #include <libxml2/libxml/schematron.h>
// #include <libxml2/libxml/uri.h>
// #include <libxml2/libxml/valid.h>
// #include <libxml2/libxml/xinclude.h>
// #include <libxml2/libxml/xmlIO.h>
// #include <libxml2/libxml/xmlautomata.h>
// #include <libxml2/libxml/xmlerror.h>
// #include <libxml2/libxml/xmlexports.h>
// #include <libxml2/libxml/xmlmodule.h>
// #include <libxml2/libxml/xmlreader.h>
// #include <libxml2/libxml/xmlregexp.h>
// #include <libxml2/libxml/xmlsave.h>
// #include <libxml2/libxml/xmlschemas.h>
// #include <libxml2/libxml/xmlschemastypes.h>
// #include <libxml2/libxml/xmlstring.h>
// #include <libxml2/libxml/xmlunicode.h>
// #include <libxml2/libxml/xmlversion.h>
// #include <libxml2/libxml/xmlwriter.h>
// #include <libxml2/libxml/xpath.h>
// #include <libxml2/libxml/xpathInternals.h>
// #include <libxml2/libxml/xpointer.h>
// #include <GLES2/gl2ext.h>
// #include <GLES2/gl2.h>
// #include <GLES3/gl3ext.h>
// #include <GLES3/gl3.h>
// #include <EGL/egl.h>
// #include <GLES/glext.h>
// #include <GLES/gl.h>
// #include <unicode/localpointer.h>
// #include <unicode/parseerr.h>
// #include <unicode/platform.h>
// #include <unicode/ptypes.h>
// #include <unicode/putil.h>
// #include <unicode/uchar.h>
// #include <unicode/uconfig.h>
// #include <unicode/uiter.h>
// #include <unicode/umachine.h>
// #include <unicode/uregex.h>
// #include <unicode/urename.h>
// #include <unicode/ustring.h>
// #include <unicode/utext.h>
// #include <unicode/utf.h>
// #include <unicode/utf16.h>
// #include <unicode/utf8.h>
// #include <unicode/utf_old.h>
// #include <unicode/utypes.h>
// #include <unicode/uvernum.h>
// #include <unicode/uversion.h>
#include <zlib.h>
